#!/usr/bin/env python3

import argparse

from Herne.Core import app_run

_parser = argparse.ArgumentParser()

_parser.add_argument('options', nargs='+', type=str)

args = _parser.parse_args()

for opt in args.options:
    exec(open(opt).read())

for app in app_run():
    with app as a:
    	a()
