name: Herne
on: [ push ]
jobs:
        build:
                name: Herne (${{ matrix.os }} ${{ matrix.python-version }} )
                runs-on: ${{ matrix.os }}
                strategy:
                        matrix:
                                os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest']
                                python-version: [3.7, 3.8]
                steps:
                        - uses: actions/checkout@v2
                        - name: Setup Python
                          uses: actions/setup-python@v2
                          with:
                                  python-version: ${{ matrix.python-version }}
                        - name: Install Dependencies
                          run: pip3 install --upgrade pip && pip3 install -r requirements.txt

                        - name: Install Herne
                          run: pip3 install .

                        - name: Run tests
                          run: python -m unittest tests/test_herne.py
